name: Check Markdown Grammar

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  write-good:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install write-good
        run: npm install -g write-good
      - name: Run write-good
        run: |
          files=$(git ls-files '*.md')
          if [ -n "$files" ]; then
            write-good $files
          else
            echo "No Markdown files found."
          fi

  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Vale
        uses: errata-ai/vale-action@v2.1.1
        with:
          files: .
          vale_flags: --glob=*.md
          reporter: local
          fail_on_error: true
